---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: rag-secret
  namespace: rag

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: rag-secret
    creationPolicy: Owner

  data:
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: rag/gemini-api-key

    - secretKey: API_TOKEN
      remoteRef:
        key: rag/api-token
