---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: trivy-operator
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: 0.27.1

    helm:
      values: |
        trivy:
          ignoreUnfixed: false
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

        operator:
          scanJobsConcurrentLimit: 3
          vulnerabilityScannerEnabled: true
          configAuditScannerEnabled: true
          rbacAssessmentScannerEnabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
