---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: grafana
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.10.1

    helm:
      values: |
        admin:
          existingSecret: grafana-admin-secret
          userKey: admin-user
          passwordKey: admin-password

        persistence:
          enabled: true
          size: 10Gi

        service:
          type: ClusterIP

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
                isDefault: true

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi

        grafana.ini:
          security:
            allow_embedding: false
          users:
            allow_sign_up: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
